/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Order.Order;
import EcoSystem.Order.OrderItem;
import EcoSystem.Order.OrderList;
import EcoSystem.Organization.CustomerOrganization;
import EcoSystem.Organization.Organization;
import EcoSystem.Organization.StoreOrganization;
import EcoSystem.Organization.StoreOrganization.StoreType;
import EcoSystem.Product.Product;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucy Bai
 */
public class OrderProduct extends javax.swing.JPanel {

    /**
     * Creates new form OrderProduct
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Order order;
    private OrderList orderList;
    private EcoSystem system;
    private CustomerOrganization customerOrganization;

   public OrderProduct(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system, CustomerOrganization customerOrganization) {
        initComponents();
        this.account=account;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        order = new Order();
        this.customerOrganization = customerOrganization;
        orderList = customerOrganization.getOrderList();
        
        populateTypeComboBox();
        populateComboBox();
        populateTable();
     
    }
    
   public void populateComboBox() {
       
       comboStore.removeAllItems();
       for( Organization organization: enterprise.getOrganizationDirectory().getOrganizationList() ) {
           if( organization instanceof StoreOrganization ) {
               StoreOrganization so = (StoreOrganization) organization;
               comboStore.addItem(so);
           }
       }
   }
   
   public void populateTypeComboBox(){
       comboType.removeAllItems();
       comboType.addItem("All Stores");
            for(StoreType type: StoreOrganization.StoreType.values()){
              comboType.addItem(type);
        }
           
        
    }
    public void populateTable() {
       
        DefaultTableModel dtm = (DefaultTableModel) tblProducts.getModel();
        dtm.setRowCount(0);
        StoreOrganization so = (StoreOrganization) comboStore.getSelectedItem();
        if(so != null){
            for( Product p: so.getProducts().getProducts() ) {
                Object row[] = new Object[4];
                row[0] = p;
                row[1] = p.getPrice();
                row[2] = p.getQuatity();
                dtm.addRow(row);
            }
        }
    }
   
    public void refreshOrderTable() {
       
        DefaultTableModel model = (DefaultTableModel)tblCart.getModel();
        model.setRowCount(0);
      
        for(OrderItem oi: order.getOrderItemList()) {
            Object row[]= new Object[5];
            row[0] = oi;
            row[1] = oi.getStoreOrganization().getStoreType();
            row[2] = oi.getSalesPrice();
            row[3] = oi.getQuantity();
            row[4] = oi.getStoreOrganization();
            model.addRow(row);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboStore = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox();
        loginPanel = new javax.swing.JPanel();
        btnViewProduct = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        spinnerQuantity = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        spinnerModQty = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btnremove = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Simple Life Simple Choice");

        btnBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addGap(104, 104, 104)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1)))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1230, 50));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        tblProducts.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProducts);
        if (tblProducts.getColumnModel().getColumnCount() > 0) {
            tblProducts.getColumnModel().getColumn(0).setResizable(false);
            tblProducts.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Store Name:");

        comboStore.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comboStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStoreActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Store Type:");

        comboType.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboStore, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275)
                        .addComponent(jLabel5)
                        .addGap(49, 49, 49)
                        .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboStore, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboType))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 1230, 300));

        loginPanel.setBackground(new java.awt.Color(32, 47, 90));

        btnViewProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnViewProduct.setText("View Product Detail");
        btnViewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cart", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Type", "Price", "Quantity", "Store"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setResizable(false);
            tblCart.getColumnModel().getColumn(2).setResizable(false);
            tblCart.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity:");

        spinnerQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        spinnerQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnAdd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnAdd.setText("Add To Cart");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnModify.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        spinnerModQty.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        spinnerModQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modify Quantity:");

        btnremove.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnremove.setText("Remove Item");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        btnPlaceOrder.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnPlaceOrder.setText("Place order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(btnViewProduct)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(btnAdd))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(spinnerModQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewProduct)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(spinnerQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(spinnerModQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1230, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProducts.getSelectedRow();
        if( selectedRow >= 0 ) {
            //Need more validation
            
            Product p = (Product) tblProducts.getValueAt(selectedRow, 0);
            ViewProductDetail vpd = new ViewProductDetail(userProcessContainer, p);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add(vpd);
            layout.next(userProcessContainer);
        }
        else {
            JOptionPane.showMessageDialog(null, "No row selected", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewProductActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProducts.getSelectedRow();
        if( selectedRow >= 0 ) {
            Product p = (Product) tblProducts.getValueAt(selectedRow, 0);
            int fetchQty=(Integer)spinnerQuantity.getValue();
            //Add Validation
            if(fetchQty<=0){
                JOptionPane.showMessageDialog(null, "Quantity cannot be less than 0");
                return;
            }
            double salesPrice = p.getPrice();
            if(fetchQty <= p.getQuatity()) {
                boolean alreadyPresent = false;
                if(order.getOrderItemList() != null )
                for(OrderItem oi: order.getOrderItemList()){
                    if(oi.getP() == p){
                        oi.setQuantity(oi.getQuantity()+fetchQty);
                        oi.setSalesPrice(oi.getSalesPrice()+fetchQty*(p.getPrice()));
                        alreadyPresent=true;                        
                    }
                }  
                  if(!alreadyPresent){
                      order.addOrderItem((StoreOrganization)comboStore.getSelectedItem(), fetchQty, fetchQty*(p.getPrice()), p);                 
                    }
              p.setQuatity(p.getQuatity()-fetchQty);
              populateTable();
            refreshOrderTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row!", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStoreActionPerformed
        // TODO add your handling code here:
        
        populateTable();
    }//GEN-LAST:event_comboStoreActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
        if(comboType.getSelectedIndex() > 1) {
            StoreType st = (StoreType) comboType.getSelectedItem();
            String s =st.getValue();
            if (st!= null){
                populateSelectedStore(s);
            }
        }
        else {
            populateComboBox();
        }
    }//GEN-LAST:event_comboTypeActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
         int slectedRow=tblCart.getSelectedRow();
        if(slectedRow<0){
            JOptionPane.showMessageDialog(null, "Please Select a row");
            return;
        }
        else{
         OrderItem oi = (OrderItem)tblCart.getValueAt(slectedRow,0);
           int currentAvail = oi.getP().getQuatity();
           int oldQty=oi.getQuantity();
           int newQty=(Integer)spinnerModQty.getValue();
           if(newQty>(currentAvail+oldQty)){
                JOptionPane.showMessageDialog(null, "Quantity is more than availibility");
                return;
           }
           else{
               if(newQty<=0){
                    JOptionPane.showMessageDialog(null, "Quantity should more than 0");
                   
               }
               oi.setQuantity(newQty);
               for(Product p:oi.getStoreOrganization().getProducts().getProducts()) {
              if(p.equals(oi.getP())){
                      p.setQuatity(currentAvail+(oldQty-newQty));
              }
              
          }
               populateTable();
               refreshOrderTable();
           }
           
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        int slectedRow=tblCart.getSelectedRow();
        if(slectedRow<0){
            JOptionPane.showMessageDialog(null, "Please Select a row");
            return;
        }       
        OrderItem oi = (OrderItem)tblCart.getValueAt(slectedRow,0);
           int oldAvail =oi.getP().getQuatity();
           int oldQty=oi.getQuantity();
           int newQty=oldAvail+oldQty;
          for(Product p:oi.getStoreOrganization().getProducts().getProducts())
          {
              if(p.equals(oi.getP())){
                  p.setQuatity(newQty);
              }
          }
           order.removeOrderitem(oi);
            JOptionPane.showMessageDialog(null, "Item has removed form cart!");
            refreshOrderTable();
            populateTable();
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:

        if(tblCart.getColumnCount() >= 0) {
            orderList.addOrder(order);       
            order.setUserAccount(account);
            JOptionPane.showMessageDialog(null, "Order Placed successfully!");
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.setRowCount(0);

            CheckOutProduct viewOrder = new CheckOutProduct(userProcessContainer,account,order,enterprise,system);
            userProcessContainer.add("myOrders", viewOrder);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed
   public void populateSelectedStore(String st){
       comboStore.removeAllItems();
       for( Organization organization: enterprise.getOrganizationDirectory().getOrganizationList() ) {
           if( organization instanceof StoreOrganization ) {
               StoreOrganization so = (StoreOrganization) organization;
               if(so.getStoreType().getValue().equals(st))
                 comboStore.addItem(so);
           }
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnViewProduct;
    private javax.swing.JButton btnremove;
    private javax.swing.JComboBox comboStore;
    private javax.swing.JComboBox comboType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JSpinner spinnerModQty;
    private javax.swing.JSpinner spinnerQuantity;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
